#!/usr/bin/env -S deno run -A
import { conditions, job, workflow } from "jsr:@david/gagen@^0.5.0";

const checkUpdatesJob = job("check_updates", {
  name: "check_updates",
  if: conditions.isRepository("apcamargo/dprint-plugin-bibtex-tidy"),
  runsOn: "ubuntu-latest",
  timeoutMinutes: 45,
  steps: [
    {
      uses: "actions/checkout@v6",
      with: { "token": "${{ secrets.GH_WORKFLOW_TOKEN }}" },
    },
    { uses: "dsherret/rust-toolchain-file@v1" },
    { run: "rustup target add wasm32-unknown-unknown" },
    {
      uses: "denoland/setup-deno@v2",
      with: { "deno-version": "v2.x" },
    },
    {
      uses: "actions/setup-node@v6",
      with: { "node-version": "22" },
    },
    {
      name: "Install npm dependencies",
      run: "npm ci",
    },
    {
      name: "Run update script",
      run: "deno run -A --frozen ./scripts/update.ts",
    },
  ],
});

const keepAliveJob = job("workflow-keepalive", {
  name: "workflow-keepalive",
  if: conditions.isEvent("schedule"),
  runsOn: "ubuntu-latest",
  permissions: { actions: "write" },
  steps: [
    {
      uses: "liskin/gh-workflow-keepalive@f72ff1a1336129f29bf0166c0fd0ca6cf1bcb38c",
    },
  ],
});

workflow({
  name: "Check Updates",
  on: {
    schedule: [{ cron: "0 7 1 * *" }],
    workflow_dispatch: {},
  },
  jobs: [checkUpdatesJob, keepAliveJob],
}).writeOrLint({
  filePath: new URL("./check_updates.generated.yml", import.meta.url),
  header: "# GENERATED BY ./check_updates.ts -- DO NOT DIRECTLY EDIT",
  pinDeps: true,
});
