#!/usr/bin/env -S deno run -A
import { conditions, defineMatrix, expr, job, step, workflow } from "jsr:@david/gagen@^0.5.0";

const pluginName = "bibtex_tidy";
const cargoWasmName = `dprint_plugin_${pluginName}`;

const matrix = defineMatrix({
  config: [
    { os: "ubuntu-latest", kind: "test_release" },
    { os: "ubuntu-latest", kind: "test_debug" },
  ],
});

const kind = expr("matrix.config.kind");
const os = expr("matrix.config.os");

const isRelease = kind.equals("test_release");
const isDebug = kind.equals("test_debug");
const isTag = conditions.isTag();
const isCanonicalRepository = conditions.isRepository(
  "apcamargo/dprint-plugin-bibtex-tidy",
);
const isReleaseAndTag = isRelease.and(isTag).and(isCanonicalRepository);

const getTagVersion = step({
  id: "get_tag_version",
  name: "Get tag version",
  if: isReleaseAndTag,
  run: `echo "TAG_VERSION=\${GITHUB_REF/refs\\/tags\\//}" >> "$GITHUB_OUTPUT"`,
  outputs: ["TAG_VERSION"],
});

const buildJob = job("build", {
  name: `${kind} ${os}`,
  runsOn: os,
  strategy: { matrix },
  env: {
    CARGO_INCREMENTAL: 0,
    RUST_BACKTRACE: "full",
  },
  permissions: { contents: "read" },
  steps: [
    { uses: "actions/checkout@v6" },
    { uses: "dsherret/rust-toolchain-file@v1" },
    {
      name: "Install wasm32 target",
      if: isRelease,
      run: "rustup target add wasm32-unknown-unknown",
    },
    {
      uses: "Swatinem/rust-cache@v2",
      with: { "save-if": "${{ github.ref == 'refs/heads/main' }}" },
    },
    {
      uses: "denoland/setup-deno@v2",
      with: { "deno-version": "v2.x" },
    },
    {
      uses: "actions/setup-node@v6",
      with: { "node-version": "22" },
    },
    {
      name: "Install npm dependencies",
      run: "npm ci",
    },
    {
      name: "Build JS bundle",
      run: "node scripts/build_bundle.js",
    },

    { name: "Format check", if: isDebug, run: "cargo fmt --all -- --check" },
    { name: "Build debug", if: isDebug, run: "cargo build --locked" },
    {
      name: "Build release",
      if: isRelease,
      run: "cargo build --locked --target wasm32-unknown-unknown --features wasm --release",
    },

    { name: "Test debug", if: isDebug, run: "cargo test --locked" },
    {
      name: "Test release",
      if: isRelease,
      run: "cargo test --locked --release",
    },

    {
      name: "Clippy",
      if: isDebug,
      run: "cargo clippy --locked --all-targets --all-features -- -D warnings",
    },

    getTagVersion,

    // GITHUB RELEASE
    {
      name: "Pre-release",
      if: isReleaseAndTag,
      run: [
        "# stamp the release version into the schema $id",
        `sed -i 's|/releases/download/0.0.0/schema.json|/releases/download/'"\${{ steps.get_tag_version.outputs.TAG_VERSION }}"'/schema.json|' deployment/schema.json`,
        "# rename the wasm file",
        `(cd target/wasm32-unknown-unknown/release/ && mv ${cargoWasmName}.wasm plugin.wasm)`,
        "# create release notes",
        `deno run -A --frozen ./scripts/generate_release_notes.ts \${{ steps.get_tag_version.outputs.TAG_VERSION }} > \${{ github.workspace }}-CHANGELOG.txt`,
      ],
    },
    {
      name: "Release",
      uses: "softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844",
      if: isReleaseAndTag,
      env: { GITHUB_TOKEN: "${{ secrets.GH_WORKFLOW_TOKEN }}" },
      with: {
        files: [
          "target/wasm32-unknown-unknown/release/plugin.wasm",
          "deployment/schema.json",
        ].join("\n"),
        body_path: "${{ github.workspace }}-CHANGELOG.txt",
        draft: false,
      },
    },
    {
      name: "Lint workflow generation",
      if: isDebug,
      run: [
        "deno run -A --frozen ./.github/workflows/ci.ts --lint",
        "deno run -A --frozen ./.github/workflows/release.ts --lint",
        "deno run -A --frozen ./.github/workflows/check_updates.ts --lint",
      ],
    },
  ],
});

workflow({
  name: "CI",
  on: {
    pull_request: { branches: ["main"] },
    push: { branches: ["main"], tags: ["*"] },
  },
  jobs: [buildJob],
}).writeOrLint({
  filePath: new URL("./ci.generated.yml", import.meta.url),
  header: "# GENERATED BY ./ci.ts -- DO NOT DIRECTLY EDIT",
  pinDeps: true,
});
