#!/usr/bin/env -S deno run -A
import { job, workflow } from "jsr:@david/gagen@^0.5.0";

const releaseJob = job("release", {
  name: "release",
  runsOn: "ubuntu-latest",
  timeoutMinutes: 30,
  steps: [
    {
      uses: "actions/checkout@v6",
      with: { "token": "${{ secrets.GH_WORKFLOW_TOKEN }}" },
    },
    {
      uses: "denoland/setup-deno@v2",
      with: { "deno-version": "v2.x" },
    },
    { uses: "dsherret/rust-toolchain-file@v1" },
    {
      name: "Configure git",
      run: [
        `git config user.name "github-actions[bot]"`,
        `git config user.email "41898282+github-actions[bot]@users.noreply.github.com"`,
      ],
    },
    {
      name: "Publish Release",
      env: {
        GITHUB_TOKEN: "${{ secrets.GH_WORKFLOW_TOKEN }}",
        GH_WORKFLOW_ACTOR: "${{ github.actor }}",
      },
      run:
        `deno run -A --frozen jsr:@dprint/automation@0.12.2/tasks/publish-release --\${{ github.event.inputs.releaseKind }}`,
    },
  ],
});

workflow({
  name: "Release",
  on: {
    workflow_dispatch: {
      inputs: {
        releaseKind: {
          description: "The kind of release (patch, minor)",
          required: true,
          default: "patch",
          type: "choice",
          options: ["patch", "minor"],
        },
      },
    },
  },
  jobs: [releaseJob],
}).writeOrLint({
  filePath: new URL("./release.generated.yml", import.meta.url),
  header: "# GENERATED BY ./release.ts -- DO NOT DIRECTLY EDIT",
  pinDeps: true,
});
